all::
	tar -C etfg_i386 -xf etfg_i386/etfg_i386.tgz 
	tar -C etfg_x64  -xf etfg_x64/etfg_x64.tgz  
	tar -C i386_i386 -xf i386_i386/i386_i386.tgz 

clean:
	rm -f etfg_i386/*.so etfg_i386/*.a
	rm -f etfg_x64/*.so etfg_x64/*.a
	rm -f i386_i386/*.so i386_i386/*.a

.PHONY: all clean
